# Generated by Django 5.2.8 on 2025-11-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("image_urls", models.JSONField(blank=True, default=list)),
                ("is_enabled", models.BooleanField(default=True)),
                ("link", models.URLField(blank=True, default="#")),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
    ]
