# Generated by Django 5.2.8 on 2025-11-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["order"], "verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Order in which category appears on the landing page",
            ),
        ),
    ]
