# Generated by Django 5.2.7 on 2025-10-17 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
