# Generated by Django 5.2.7 on 2025-11-08 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_productimage_image_productimage_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_cod_available',
            new_name='is_available_for_cod',
        ),
    ]
