# Generated by Django 5.2.8 on 2025-11-16 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_is_cod_available_product_is_available_for_cod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': []},
        ),
    ]
