# Generated by Django 5.2.8 on 2026-01-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_brand_alter_size_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': []},
        ),
        migrations.AlterField(
            model_name='size',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
