# Generated by Django 6.0 on 2026-01-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0002_subscription_unsubscribed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
