# Generated by Django 5.2.8 on 2025-11-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
