# Generated by Django 5.2.8 on 2025-12-26 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_options_order_paid_at_order_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_order_c_cd5b49_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_user_id_a87c6f_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_created_0e92de_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_payment_id',
        ),
    ]
