# Generated by Django 5.2.8 on 2025-12-28 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_productrating_delete_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductRating',
        ),
    ]
