# Generated by Django 5.2.8 on 2026-01-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_returnrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_attempts',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
