# Generated by Django 5.2.8 on 2026-01-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_order_payment_attempts_order_payment_failure_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(),
        ),
    ]
